### PR TITLE
Adding ARINC424-23 document

### PR DESCRIPTION
**Pull request by bleve97**
Hi Jack, updated ARINC specs, the Boeing/Jeppesen data set breaks ARINC 424-18 (and -23, it's gone into huge detail in the data definition document)

### CODE REVIEW

**Comment by jack-laverty** [comment]
Hi, thanks for letting me know. Please update your pull request to reflect the latest commit in your fork that removes the file bound by an NDA.

**Comment by bleve97** [comment]
Done, I think

**Comment by jack-laverty** [comment]
FYI I just edited your pull request to reselect the branch and it brought the second commit in.

**Review by jack-laverty — APPROVED** [review]

**Comment by jack-laverty** [comment]
Hi,

You wouldn't have a copy of the latest jeppesen data by any chance? I would
like to test the library with it.

Cheers,
Jack

**Pull request merged**
